import type { RelatedTool, ToolPageData } from "./types"

type LocaleKey = "en" | "zh-CN" | "ja" | "ko" | "es"
type LocaleCollagePages = Record<LocaleKey, Record<string, ToolPageData>>

interface CollagePageSeed {
  slug: string
  title: string
  description: string
  ogTitle: string
  ogDescription: string
  overline: string
  headlinePart1: string
  headlineAccent: string
  headlinePart2: string
  heroDescription: string
  scenarios: ToolPageData["scenarios"]
  faqEntries: ToolPageData["faqEntries"]
}

const relatedTools: Record<LocaleKey, RelatedTool[]> = {
  en: [
    { slug: "/collage", title: "Photo Collage Maker", description: "Combine multiple photos into one private browser-based collage." },
    { slug: "/resize", title: "Image Resizer", description: "Crop and resize images before adding them to a collage." },
    { slug: "/watermark", title: "Watermark Tool", description: "Add text or logo marks to finished collage exports." },
  ],
  "zh-CN": [
    { slug: "/collage", title: "照片拼图工具", description: "在浏览器中把多张照片组合成一张拼贴图。" },
    { slug: "/resize", title: "调整图片尺寸", description: "拼图前先裁剪或调整图片尺寸。" },
    { slug: "/watermark", title: "水印工具", description: "给完成的拼图添加文字或 Logo 水印。" },
  ],
  ja: [
    { slug: "/collage", title: "写真コラージュ作成", description: "複数の写真をブラウザ内で1枚のコラージュにまとめます。" },
    { slug: "/resize", title: "画像リサイズ", description: "コラージュ前に画像を切り抜き・リサイズ。" },
    { slug: "/watermark", title: "ウォーターマーク", description: "完成したコラージュにテキストやロゴを追加。" },
  ],
  ko: [
    { slug: "/collage", title: "사진 콜라주 만들기", description: "여러 사진을 브라우저에서 하나의 콜라주로 합치세요." },
    { slug: "/resize", title: "이미지 크기 조정", description: "콜라주 전에 이미지를 자르거나 크기를 조정하세요." },
    { slug: "/watermark", title: "워터마크 도구", description: "완성된 콜라주에 텍스트나 로고를 추가하세요." },
  ],
  es: [
    { slug: "/collage", title: "Creador de Collages", description: "Combina varias fotos en un collage privado desde el navegador." },
    { slug: "/resize", title: "Redimensionar Imagen", description: "Recorta o redimensiona imágenes antes de usarlas en un collage." },
    { slug: "/watermark", title: "Marca de Agua", description: "Añade texto o logo al collage exportado." },
  ],
}

const howToSteps: Record<LocaleKey, ToolPageData["howToSteps"]> = {
  en: [
    { stepNumber: 1, title: "Upload Photos", description: "Add PNG, JPEG, or WebP images. Files stay in your browser." },
    { stepNumber: 2, title: "Choose a Layout", description: "Pick a collage template, then assign, drag, scale, rotate, or fit each photo." },
    { stepNumber: 3, title: "Export", description: "Set spacing, margin, radius, background, and download PNG, JPEG, or WebP." },
  ],
  "zh-CN": [
    { stepNumber: 1, title: "上传照片", description: "添加 PNG、JPEG 或 WebP 图片，文件保留在浏览器本地。" },
    { stepNumber: 2, title: "选择布局", description: "选择拼图模板，然后为每个格子分配、拖动、缩放、旋转或适配照片。" },
    { stepNumber: 3, title: "导出", description: "设置间距、边距、圆角和背景，下载 PNG、JPEG 或 WebP。" },
  ],
  ja: [
    { stepNumber: 1, title: "写真をアップロード", description: "PNG、JPEG、WebP画像を追加。ファイルはブラウザ内に留まります。" },
    { stepNumber: 2, title: "レイアウトを選択", description: "テンプレートを選び、各写真を割り当て、ドラッグ、拡大、回転、フィットします。" },
    { stepNumber: 3, title: "書き出し", description: "間隔、余白、角丸、背景を調整し、PNG、JPEG、WebPで保存します。" },
  ],
  ko: [
    { stepNumber: 1, title: "사진 업로드", description: "PNG, JPEG, WebP 이미지를 추가하세요. 파일은 브라우저에 머뭅니다." },
    { stepNumber: 2, title: "레이아웃 선택", description: "템플릿을 고르고 각 사진을 배치, 드래그, 확대, 회전 또는 맞춤 처리하세요." },
    { stepNumber: 3, title: "내보내기", description: "간격, 여백, 둥근 모서리, 배경을 설정하고 PNG, JPEG, WebP로 저장하세요." },
  ],
  es: [
    { stepNumber: 1, title: "Sube fotos", description: "Añade PNG, JPEG o WebP. Los archivos permanecen en tu navegador." },
    { stepNumber: 2, title: "Elige un diseño", description: "Selecciona una plantilla y ajusta cada foto con arrastre, escala, rotación o ajuste." },
    { stepNumber: 3, title: "Exporta", description: "Configura espacios, margen, bordes, fondo y descarga PNG, JPEG o WebP." },
  ],
}

const seeds: Record<LocaleKey, CollagePageSeed[]> = {
  en: [
    {
      slug: "photo-collage-maker",
      title: "Photo Collage Maker Online - Free & Private | ImgSplit",
      description: "Create photo collages online with templates, spacing, backgrounds, and browser-based export. Free, private, no upload required.",
      ogTitle: "Photo Collage Maker Online",
      ogDescription: "Combine multiple photos into one clean collage in your browser.",
      overline: "Photo Collage Maker",
      headlinePart1: "Make ",
      headlineAccent: "Photo Collages",
      headlinePart2: "Online",
      heroDescription: "Combine travel shots, product images, event photos, or social posts into a polished collage with templates, spacing, backgrounds, and private browser export.",
      scenarios: [
        { icon: "Images", title: "Memory Sets", description: "Combine family, travel, event, and celebration photos into one balanced image." },
        { icon: "LayoutTemplate", title: "Fast Template Layouts", description: "Start from two-photo, grid, mosaic, and story templates instead of arranging from scratch." },
      ],
      faqEntries: [
        { question: "Is this collage maker private?", answer: "Yes. Images are loaded, arranged, and exported locally in your browser." },
        { question: "Can I adjust each photo inside its frame?", answer: "Yes. Select a frame to drag, fit, fill, scale, or rotate the assigned photo." },
        { question: "What formats can I export?", answer: "You can export the collage as PNG, JPEG, or WebP." },
      ],
    },
    {
      slug: "photo-grid-maker",
      title: "Photo Grid Maker Online - Free Browser Tool | ImgSplit",
      description: "Make a photo grid online with 2, 3, 4, 5, or 6-image layouts. Adjust spacing, margins, backgrounds, and export privately.",
      ogTitle: "Photo Grid Maker Online",
      ogDescription: "Create clean photo grids with browser-based templates.",
      overline: "Photo Grid Maker",
      headlinePart1: "Build ",
      headlineAccent: "Photo Grids",
      headlinePart2: "Fast",
      heroDescription: "Create structured photo grids for portfolios, product sets, moodboards, and social posts. Tune spacing, margins, corners, and background color.",
      scenarios: [
        { icon: "Grid3X3", title: "Product or Portfolio Sets", description: "Show multiple images in a clean grid with consistent spacing and export size." },
        { icon: "Palette", title: "Moodboards", description: "Collect colors, textures, references, and image studies into one shareable grid." },
      ],
      faqEntries: [
        { question: "Can I make a 2x2 photo grid?", answer: "Yes. Use the four-grid template and drop one image into each frame." },
        { question: "Can I change the grid border spacing?", answer: "Yes. Use the spacing and margin sliders to control inner gaps and outer padding." },
        { question: "Can I export a square grid?", answer: "Yes. The default artboard is 1080 x 1080, and you can choose other sizes." },
      ],
    },
    {
      slug: "instagram-story-collage",
      title: "Instagram Story Collage Maker - 1080x1920 | ImgSplit",
      description: "Create a 1080x1920 Instagram Story collage online. Use story templates, spacing, backgrounds, and private browser export.",
      ogTitle: "Instagram Story Collage Maker",
      ogDescription: "Make vertical story collages at 1080x1920.",
      overline: "Instagram Story Collage",
      headlinePart1: "Create ",
      headlineAccent: "Story Collages",
      headlinePart2: "Online",
      heroDescription: "Arrange photos into a vertical 1080x1920 story collage with a hero frame, supporting images, clean spacing, and export-ready dimensions.",
      scenarios: [
        { icon: "Smartphone", title: "Story Recaps", description: "Combine event, travel, food, outfit, or product shots into one vertical story image." },
        { icon: "Share2", title: "Social Posting", description: "Export a finished portrait collage ready for Instagram Stories and similar vertical formats." },
      ],
      faqEntries: [
        { question: "What size is the story collage?", answer: "The story preset uses 1080 x 1920 pixels, a common 9:16 vertical format." },
        { question: "Can I use a square collage instead?", answer: "Yes. Switch the output size to the square artboard or choose another template." },
        { question: "Will my photos upload to a server?", answer: "No. The collage is rendered in your browser." },
      ],
    },
    {
      slug: "free-photo-collage-maker",
      title: "Free Photo Collage Maker Online | ImgSplit",
      description: "Make a free photo collage online with templates, grid layouts, spacing, backgrounds, and private browser export.",
      ogTitle: "Free Photo Collage Maker",
      ogDescription: "Create free photo collages in your browser without uploading files.",
      overline: "Free Photo Collage Maker",
      headlinePart1: "Create a ",
      headlineAccent: "Free Photo Collage",
      headlinePart2: "Online",
      heroDescription: "Turn multiple photos into a polished collage without sign-up or upload. Pick a template, tune the layout, and export PNG, JPEG, or WebP from your browser.",
      scenarios: [
        { icon: "Sparkles", title: "No-Signup Collages", description: "Make quick birthday, travel, family, product, or event collages without creating an account." },
        { icon: "ShieldCheck", title: "Private Browser Export", description: "Keep personal photos local while arranging and downloading the final collage." },
      ],
      faqEntries: [
        { question: "Is the photo collage maker free?", answer: "Yes. You can upload photos, choose templates, adjust styling, and export from the browser." },
        { question: "Do I need an account?", answer: "No. The collage editor opens immediately and works without sign-up." },
        { question: "Are my photos uploaded?", answer: "No. Files stay in your browser while you create and export the collage." },
      ],
    },
    {
      slug: "picture-grid-maker",
      title: "Picture Grid Maker Online - Free & Private | ImgSplit",
      description: "Create a picture grid online for product sets, moodboards, portfolios, and social posts. Adjust spacing and export privately.",
      ogTitle: "Picture Grid Maker Online",
      ogDescription: "Build clean picture grids with private browser export.",
      overline: "Picture Grid Maker",
      headlinePart1: "Make a ",
      headlineAccent: "Picture Grid",
      headlinePart2: "Online",
      heroDescription: "Arrange pictures into clean grid layouts with consistent gaps, corners, and backgrounds. Use it for image sets, comparisons, references, and social visuals.",
      scenarios: [
        { icon: "Grid3X3", title: "Picture Sets", description: "Place related images into two, three, four, five, or six-frame layouts with consistent spacing." },
        { icon: "Images", title: "Visual Comparisons", description: "Compare product shots, before-and-after images, references, or creative directions in one export." },
      ],
      faqEntries: [
        { question: "What is the difference between a picture grid and a collage?", answer: "A picture grid is more structured, with repeated frames and consistent spacing. You can still adjust each image inside its frame." },
        { question: "Can I make a square picture grid?", answer: "Yes. Use the square artboard and choose a grid template." },
        { question: "Can I leave some grid spaces empty?", answer: "Yes. Empty frames can be filled later by clicking or dropping a file into the frame." },
      ],
    },
    {
      slug: "instagram-collage-maker",
      title: "Instagram Collage Maker Online | ImgSplit",
      description: "Create Instagram collages for posts, stories, recaps, and product sets. Use square or vertical templates with private export.",
      ogTitle: "Instagram Collage Maker",
      ogDescription: "Make Instagram-ready photo collages in your browser.",
      overline: "Instagram Collage Maker",
      headlinePart1: "Design ",
      headlineAccent: "Instagram Collages",
      headlinePart2: "Online",
      heroDescription: "Create square feed collages, vertical story layouts, recap posts, or product sets with templates sized for social sharing and browser-based export.",
      scenarios: [
        { icon: "Instagram", title: "Feed and Story Layouts", description: "Switch between square collage boards and 1080x1920 vertical story templates." },
        { icon: "Share2", title: "Social Recaps", description: "Combine outfits, trips, food, events, or product angles into a single Instagram-ready image." },
      ],
      faqEntries: [
        { question: "Can I make collages for both Instagram posts and Stories?", answer: "Yes. Use a square layout for feed posts or a 1080 x 1920 layout for Stories." },
        { question: "Can I control spacing and rounded corners?", answer: "Yes. Adjust spacing, margins, radius, background, and transparent export settings." },
        { question: "Does this work on mobile?", answer: "Yes. The editor is browser-based and can be used on desktop or mobile browsers." },
      ],
    },
  ],
  "zh-CN": [
    {
      slug: "photo-collage-maker",
      title: "在线照片拼图工具 - 免费私密 | ImgSplit",
      description: "使用模板、间距、背景和浏览器端导出创建照片拼图。免费、私密、无需上传。",
      ogTitle: "在线照片拼图工具",
      ogDescription: "在浏览器中把多张照片组合成干净的拼贴图。",
      overline: "照片拼图工具",
      headlinePart1: "在线制作",
      headlineAccent: "照片拼图",
      headlinePart2: "",
      heroDescription: "把旅行照、产品图、活动照片或社媒素材组合成精致拼图，支持模板、间距、背景和本地导出。",
      scenarios: [
        { icon: "Images", title: "回忆合集", description: "把家庭、旅行、活动和庆祝照片组合成一张平衡的图片。" },
        { icon: "LayoutTemplate", title: "快速模板布局", description: "从双图、网格、马赛克和 Story 模板开始，无需从零排版。" },
      ],
      faqEntries: [
        { question: "这个拼图工具私密吗？", answer: "是的。图片在浏览器中加载、排版和导出。" },
        { question: "可以调整每张照片的位置吗？", answer: "可以。选中格子后可拖动、适配、填充、缩放或旋转照片。" },
        { question: "支持导出什么格式？", answer: "支持导出 PNG、JPEG 或 WebP。" },
      ],
    },
    {
      slug: "photo-grid-maker",
      title: "在线照片网格工具 - 免费浏览器端 | ImgSplit",
      description: "在线制作 2、3、4、5 或 6 图照片网格，可调整间距、边距、背景并私密导出。",
      ogTitle: "在线照片网格工具",
      ogDescription: "用浏览器端模板创建干净照片网格。",
      overline: "照片网格工具",
      headlinePart1: "快速制作",
      headlineAccent: "照片网格",
      headlinePart2: "",
      heroDescription: "为作品集、产品图、情绪板和社媒帖子创建结构化照片网格，并控制间距、边距、圆角和背景色。",
      scenarios: [
        { icon: "Grid3X3", title: "产品或作品集", description: "用一致的间距和导出尺寸展示多张图片。" },
        { icon: "Palette", title: "情绪板", description: "把颜色、纹理、参考图和视觉研究整理成一张可分享网格。" },
      ],
      faqEntries: [
        { question: "可以制作 2x2 照片网格吗？", answer: "可以。选择四宫格模板，为每个格子放入一张图片。" },
        { question: "可以调整网格间距吗？", answer: "可以。使用间距和边距滑块控制内部空隙和外部留白。" },
        { question: "可以导出正方形网格吗？", answer: "可以。默认画布是 1080 x 1080，也可以选择其他尺寸。" },
      ],
    },
    {
      slug: "instagram-story-collage",
      title: "Instagram Story 拼图工具 - 1080x1920 | ImgSplit",
      description: "在线创建 1080x1920 Instagram Story 拼图，支持 Story 模板、间距、背景和浏览器端导出。",
      ogTitle: "Instagram Story 拼图工具",
      ogDescription: "制作 1080x1920 竖版 Story 拼图。",
      overline: "Instagram Story 拼图",
      headlinePart1: "创建",
      headlineAccent: "Story 拼图",
      headlinePart2: "",
      heroDescription: "用主视觉和辅助图片组合成 1080x1920 竖版 Story 拼图，尺寸适合直接导出发布。",
      scenarios: [
        { icon: "Smartphone", title: "Story 回顾", description: "把活动、旅行、美食、穿搭或产品照片组合成一张竖版 Story。" },
        { icon: "Share2", title: "社媒发布", description: "导出适合 Instagram Stories 及类似竖版格式的成品拼图。" },
      ],
      faqEntries: [
        { question: "Story 拼图尺寸是多少？", answer: "Story 预设使用 1080 x 1920 像素，也就是常见 9:16 竖版格式。" },
        { question: "可以改成正方形拼图吗？", answer: "可以。切换输出尺寸为正方形画布，或选择其他模板。" },
        { question: "照片会上传到服务器吗？", answer: "不会。拼图在浏览器中渲染完成。" },
      ],
    },
    {
      slug: "free-photo-collage-maker",
      title: "免费在线照片拼图工具 | ImgSplit",
      description: "免费在线制作照片拼图，支持模板、网格布局、间距、背景和浏览器端私密导出。",
      ogTitle: "免费照片拼图工具",
      ogDescription: "无需上传文件，在浏览器中免费制作照片拼图。",
      overline: "免费照片拼图工具",
      headlinePart1: "免费制作",
      headlineAccent: "照片拼图",
      headlinePart2: "",
      heroDescription: "无需注册或上传，把多张照片组合成精致拼图。选择模板、调整布局，并从浏览器导出 PNG、JPEG 或 WebP。",
      scenarios: [
        { icon: "Sparkles", title: "免注册拼图", description: "快速制作生日、旅行、家庭、产品或活动照片拼图，无需创建账号。" },
        { icon: "ShieldCheck", title: "浏览器私密导出", description: "照片保留在本地浏览器中，排版和下载都不经过服务器。" },
      ],
      faqEntries: [
        { question: "照片拼图工具是免费的吗？", answer: "是的。可以上传照片、选择模板、调整样式并在浏览器中导出。" },
        { question: "需要账号吗？", answer: "不需要。打开编辑器即可使用。" },
        { question: "照片会上传吗？", answer: "不会。文件会留在浏览器本地，直到你完成拼图导出。" },
      ],
    },
    {
      slug: "picture-grid-maker",
      title: "在线图片网格工具 - 免费私密 | ImgSplit",
      description: "为产品图、情绪板、作品集和社媒帖子在线创建图片网格，可调整间距并私密导出。",
      ogTitle: "在线图片网格工具",
      ogDescription: "在浏览器中制作干净的图片网格。",
      overline: "图片网格工具",
      headlinePart1: "在线制作",
      headlineAccent: "图片网格",
      headlinePart2: "",
      heroDescription: "把图片排成整洁网格，统一空隙、圆角和背景，适合图片合集、对比图、参考图和社媒视觉。",
      scenarios: [
        { icon: "Grid3X3", title: "图片合集", description: "把相关图片放进双图、三图、四图、五图或六图布局。" },
        { icon: "Images", title: "视觉对比", description: "把产品图、前后对比、参考素材或创意方向合成一张图。" },
      ],
      faqEntries: [
        { question: "图片网格和拼图有什么区别？", answer: "图片网格更结构化，通常使用重复格子和统一间距，同时也能调整每张图片的位置。" },
        { question: "可以制作正方形图片网格吗？", answer: "可以。选择正方形画布和网格模板即可。" },
        { question: "可以保留空格子吗？", answer: "可以。空格子之后可以点击或拖入文件继续填充。" },
      ],
    },
    {
      slug: "instagram-collage-maker",
      title: "Instagram 拼图工具在线版 | ImgSplit",
      description: "为 Instagram 帖子、Story、回顾和产品合集创建拼图，支持正方形或竖版模板并私密导出。",
      ogTitle: "Instagram 拼图工具",
      ogDescription: "在浏览器中制作适合 Instagram 的照片拼图。",
      overline: "Instagram 拼图工具",
      headlinePart1: "制作",
      headlineAccent: "Instagram 拼图",
      headlinePart2: "",
      heroDescription: "制作正方形 Feed 拼图、竖版 Story 布局、回顾帖或产品合集，使用适合社媒分享的模板并在浏览器中导出。",
      scenarios: [
        { icon: "Instagram", title: "Feed 与 Story 布局", description: "可在正方形拼图画布和 1080x1920 竖版 Story 模板之间切换。" },
        { icon: "Share2", title: "社媒回顾", description: "把穿搭、旅行、美食、活动或产品角度组合成一张适合 Instagram 的图片。" },
      ],
      faqEntries: [
        { question: "可以同时做 Instagram 帖子和 Story 拼图吗？", answer: "可以。Feed 使用正方形布局，Story 使用 1080 x 1920 竖版布局。" },
        { question: "可以控制间距和圆角吗？", answer: "可以。支持调整间距、边距、圆角、背景和透明导出。" },
        { question: "手机上能用吗？", answer: "可以。编辑器基于浏览器，桌面和手机浏览器都能使用。" },
      ],
    },
  ],
  ja: [
    {
      slug: "photo-collage-maker",
      title: "オンライン写真コラージュ作成 - 無料・プライベート | ImgSplit",
      description: "テンプレート、間隔、背景、ブラウザ内書き出しで写真コラージュを作成。無料でアップロード不要。",
      ogTitle: "オンライン写真コラージュ作成",
      ogDescription: "複数の写真をブラウザで1枚のコラージュに。",
      overline: "写真コラージュ",
      headlinePart1: "写真",
      headlineAccent: "コラージュ",
      headlinePart2: "を作成",
      heroDescription: "旅行、商品、イベント、SNS用の写真をテンプレート、間隔、背景つきの美しいコラージュにまとめます。",
      scenarios: [
        { icon: "Images", title: "思い出のセット", description: "家族、旅行、イベント、記念日の写真を1枚にまとめます。" },
        { icon: "LayoutTemplate", title: "高速テンプレート", description: "2枚、グリッド、モザイク、Storyテンプレートからすぐに開始できます。" },
      ],
      faqEntries: [
        { question: "このツールはプライベートですか？", answer: "はい。画像の読み込み、配置、書き出しはブラウザ内で行われます。" },
        { question: "各写真を調整できますか？", answer: "はい。フレームを選択してドラッグ、フィット、フィル、拡大、回転できます。" },
        { question: "書き出し形式は？", answer: "PNG、JPEG、WebPで書き出せます。" },
      ],
    },
    {
      slug: "photo-grid-maker",
      title: "オンライン写真グリッド作成 - 無料ブラウザツール | ImgSplit",
      description: "2、3、4、5、6枚の写真グリッドを作成。間隔、余白、背景を調整し、プライベートに書き出し。",
      ogTitle: "オンライン写真グリッド作成",
      ogDescription: "テンプレートで整った写真グリッドを作成。",
      overline: "写真グリッド",
      headlinePart1: "写真",
      headlineAccent: "グリッド",
      headlinePart2: "を作成",
      heroDescription: "ポートフォリオ、商品セット、ムードボード、SNS投稿向けに、整った写真グリッドを素早く作れます。",
      scenarios: [
        { icon: "Grid3X3", title: "商品・作品セット", description: "複数画像を一貫した間隔とサイズで見せられます。" },
        { icon: "Palette", title: "ムードボード", description: "色、質感、参考画像、ビジュアル研究を1枚のグリッドに。" },
      ],
      faqEntries: [
        { question: "2x2グリッドは作れますか？", answer: "はい。4グリッドテンプレートを使って各枠に画像を入れます。" },
        { question: "グリッド間隔は変えられますか？", answer: "はい。間隔と余白スライダーで内側と外側のスペースを調整できます。" },
        { question: "正方形で書き出せますか？", answer: "はい。標準は1080 x 1080で、他のサイズも選べます。" },
      ],
    },
    {
      slug: "instagram-story-collage",
      title: "Instagram Story コラージュ作成 - 1080x1920 | ImgSplit",
      description: "1080x1920のInstagram Storyコラージュをオンライン作成。Storyテンプレート、背景、ブラウザ書き出し対応。",
      ogTitle: "Instagram Story コラージュ",
      ogDescription: "1080x1920の縦型Storyコラージュを作成。",
      overline: "Instagram Story コラージュ",
      headlinePart1: "Story",
      headlineAccent: "コラージュ",
      headlinePart2: "を作成",
      heroDescription: "メイン写真とサブ写真を1080x1920の縦型Storyコラージュに配置し、そのまま投稿用に書き出せます。",
      scenarios: [
        { icon: "Smartphone", title: "Storyまとめ", description: "イベント、旅行、食事、コーデ、商品写真を縦型画像にまとめます。" },
        { icon: "Share2", title: "SNS投稿", description: "Instagram Storiesなどの縦型フォーマットに適した画像を書き出します。" },
      ],
      faqEntries: [
        { question: "Storyサイズはいくつですか？", answer: "Storyプリセットは一般的な9:16形式の1080 x 1920ピクセルです。" },
        { question: "正方形にもできますか？", answer: "はい。出力サイズを正方形に切り替えるか、別テンプレートを選べます。" },
        { question: "写真はアップロードされますか？", answer: "いいえ。コラージュはブラウザ内でレンダリングされます。" },
      ],
    },
    {
      slug: "free-photo-collage-maker",
      title: "無料オンライン写真コラージュ作成 | ImgSplit",
      description: "テンプレート、グリッド、間隔、背景を使って無料で写真コラージュを作成。ブラウザ内でプライベートに書き出し。",
      ogTitle: "無料写真コラージュ作成",
      ogDescription: "アップロード不要で無料の写真コラージュをブラウザ作成。",
      overline: "無料写真コラージュ",
      headlinePart1: "無料で写真",
      headlineAccent: "コラージュ",
      headlinePart2: "を作成",
      heroDescription: "登録やアップロードなしで複数写真を美しいコラージュに。テンプレートを選び、レイアウトを整えてPNG、JPEG、WebPで保存できます。",
      scenarios: [
        { icon: "Sparkles", title: "登録不要", description: "誕生日、旅行、家族、商品、イベントのコラージュをすぐ作成できます。" },
        { icon: "ShieldCheck", title: "ブラウザ内で完結", description: "個人写真をローカルに保ったまま配置し、完成画像をダウンロードします。" },
      ],
      faqEntries: [
        { question: "写真コラージュ作成は無料ですか？", answer: "はい。写真の追加、テンプレート選択、スタイル調整、書き出しができます。" },
        { question: "アカウントは必要ですか？", answer: "不要です。エディターを開いてすぐ使えます。" },
        { question: "写真はアップロードされますか？", answer: "いいえ。ファイルはブラウザ内に留まり、そこで書き出されます。" },
      ],
    },
    {
      slug: "picture-grid-maker",
      title: "オンライン画像グリッド作成 - 無料・プライベート | ImgSplit",
      description: "商品セット、ムードボード、ポートフォリオ、SNS投稿向けの画像グリッドを作成。間隔を調整してプライベートに保存。",
      ogTitle: "オンライン画像グリッド作成",
      ogDescription: "ブラウザで整った画像グリッドを作成。",
      overline: "画像グリッド",
      headlinePart1: "画像",
      headlineAccent: "グリッド",
      headlinePart2: "を作成",
      heroDescription: "画像を一貫した余白、角丸、背景のグリッドに配置。画像セット、比較、参考資料、SNSビジュアルに使えます。",
      scenarios: [
        { icon: "Grid3X3", title: "画像セット", description: "関連画像を2、3、4、5、6フレームのレイアウトに配置します。" },
        { icon: "Images", title: "ビジュアル比較", description: "商品写真、ビフォーアフター、参考画像、方向性を1枚で比較できます。" },
      ],
      faqEntries: [
        { question: "画像グリッドとコラージュの違いは？", answer: "画像グリッドは反復フレームと一定の間隔でより構造的です。各画像の位置調整もできます。" },
        { question: "正方形の画像グリッドは作れますか？", answer: "はい。正方形アートボードとグリッドテンプレートを使えます。" },
        { question: "空の枠を残せますか？", answer: "はい。空フレームは後からクリックまたはドロップで画像を追加できます。" },
      ],
    },
    {
      slug: "instagram-collage-maker",
      title: "Instagram コラージュ作成オンライン | ImgSplit",
      description: "Instagram投稿、Story、まとめ、商品セット向けコラージュを作成。正方形・縦型テンプレートに対応。",
      ogTitle: "Instagram コラージュ作成",
      ogDescription: "Instagram向け写真コラージュをブラウザで作成。",
      overline: "Instagram コラージュ",
      headlinePart1: "Instagram",
      headlineAccent: "コラージュ",
      headlinePart2: "を作成",
      heroDescription: "正方形フィード用、縦型Story用、まとめ投稿、商品セットを、SNS共有に適したテンプレートで作成しブラウザから書き出せます。",
      scenarios: [
        { icon: "Instagram", title: "FeedとStory", description: "正方形コラージュと1080x1920の縦型Storyテンプレートを切り替えられます。" },
        { icon: "Share2", title: "SNSまとめ", description: "コーデ、旅行、食事、イベント、商品写真をInstagram向けの1枚にまとめます。" },
      ],
      faqEntries: [
        { question: "Instagram投稿とStoriesの両方に使えますか？", answer: "はい。フィードには正方形、Storiesには1080 x 1920の縦型を使えます。" },
        { question: "間隔や角丸は調整できますか？", answer: "はい。間隔、余白、角丸、背景、透明書き出しを調整できます。" },
        { question: "スマホでも使えますか？", answer: "はい。ブラウザベースなのでデスクトップとモバイルで使えます。" },
      ],
    },
  ],
  ko: [
    {
      slug: "photo-collage-maker",
      title: "온라인 사진 콜라주 만들기 - 무료 비공개 | ImgSplit",
      description: "템플릿, 간격, 배경, 브라우저 내보내기로 사진 콜라주를 만드세요. 무료이며 업로드가 필요 없습니다.",
      ogTitle: "온라인 사진 콜라주 만들기",
      ogDescription: "여러 사진을 브라우저에서 깔끔한 콜라주로 합치세요.",
      overline: "사진 콜라주 만들기",
      headlinePart1: "사진",
      headlineAccent: "콜라주",
      headlinePart2: " 만들기",
      heroDescription: "여행, 제품, 행사, 소셜 사진을 템플릿, 간격, 배경과 함께 완성도 높은 콜라주로 합치세요.",
      scenarios: [
        { icon: "Images", title: "추억 모음", description: "가족, 여행, 행사, 기념일 사진을 균형 잡힌 한 장으로 만드세요." },
        { icon: "LayoutTemplate", title: "빠른 템플릿", description: "2장, 그리드, 모자이크, Story 템플릿으로 바로 시작하세요." },
      ],
      faqEntries: [
        { question: "이 콜라주 도구는 비공개인가요?", answer: "네. 이미지는 브라우저에서 불러오고 배치하고 내보냅니다." },
        { question: "각 사진을 조정할 수 있나요?", answer: "네. 프레임을 선택해 드래그, 맞춤, 채우기, 확대, 회전할 수 있습니다." },
        { question: "어떤 형식으로 내보낼 수 있나요?", answer: "PNG, JPEG, WebP로 내보낼 수 있습니다." },
      ],
    },
    {
      slug: "photo-grid-maker",
      title: "온라인 사진 그리드 만들기 - 무료 브라우저 도구 | ImgSplit",
      description: "2, 3, 4, 5, 6장 사진 그리드를 만들고 간격, 여백, 배경을 조정해 비공개로 내보내세요.",
      ogTitle: "온라인 사진 그리드 만들기",
      ogDescription: "브라우저 템플릿으로 깔끔한 사진 그리드를 만드세요.",
      overline: "사진 그리드 만들기",
      headlinePart1: "사진",
      headlineAccent: "그리드",
      headlinePart2: " 만들기",
      heroDescription: "포트폴리오, 제품 세트, 무드보드, 소셜 게시물용 구조적인 사진 그리드를 빠르게 만드세요.",
      scenarios: [
        { icon: "Grid3X3", title: "제품 또는 포트폴리오", description: "여러 이미지를 일관된 간격과 크기로 보여주세요." },
        { icon: "Palette", title: "무드보드", description: "색상, 질감, 참고 이미지, 비주얼 리서치를 하나의 그리드로 정리하세요." },
      ],
      faqEntries: [
        { question: "2x2 사진 그리드를 만들 수 있나요?", answer: "네. 4그리드 템플릿을 사용해 각 프레임에 이미지를 넣으면 됩니다." },
        { question: "그리드 간격을 바꿀 수 있나요?", answer: "네. 간격과 여백 슬라이더로 내부 간격과 외부 여백을 조정하세요." },
        { question: "정사각형 그리드로 내보낼 수 있나요?", answer: "네. 기본 아트보드는 1080 x 1080이며 다른 크기도 선택할 수 있습니다." },
      ],
    },
    {
      slug: "instagram-story-collage",
      title: "Instagram Story 콜라주 만들기 - 1080x1920 | ImgSplit",
      description: "1080x1920 Instagram Story 콜라주를 온라인에서 만드세요. Story 템플릿, 배경, 브라우저 내보내기 지원.",
      ogTitle: "Instagram Story 콜라주 만들기",
      ogDescription: "1080x1920 세로 Story 콜라주를 만드세요.",
      overline: "Instagram Story 콜라주",
      headlinePart1: "Story",
      headlineAccent: "콜라주",
      headlinePart2: " 만들기",
      heroDescription: "메인 프레임과 보조 사진을 1080x1920 세로 Story 콜라주로 배치해 바로 내보내세요.",
      scenarios: [
        { icon: "Smartphone", title: "Story 요약", description: "행사, 여행, 음식, 스타일, 제품 사진을 하나의 세로 이미지로 합치세요." },
        { icon: "Share2", title: "소셜 게시", description: "Instagram Stories와 비슷한 세로 형식에 맞는 완성 이미지를 내보내세요." },
      ],
      faqEntries: [
        { question: "Story 콜라주 크기는 얼마인가요?", answer: "Story 프리셋은 일반적인 9:16 형식인 1080 x 1920 픽셀입니다." },
        { question: "정사각형 콜라주로 바꿀 수 있나요?", answer: "네. 출력 크기를 정사각형으로 바꾸거나 다른 템플릿을 선택하세요." },
        { question: "사진이 서버에 업로드되나요?", answer: "아니요. 콜라주는 브라우저에서 렌더링됩니다." },
      ],
    },
    {
      slug: "free-photo-collage-maker",
      title: "무료 온라인 사진 콜라주 만들기 | ImgSplit",
      description: "템플릿, 그리드, 간격, 배경으로 무료 사진 콜라주를 만들고 브라우저에서 비공개로 내보내세요.",
      ogTitle: "무료 사진 콜라주 만들기",
      ogDescription: "업로드 없이 브라우저에서 무료 사진 콜라주를 만드세요.",
      overline: "무료 사진 콜라주",
      headlinePart1: "무료 사진",
      headlineAccent: "콜라주",
      headlinePart2: " 만들기",
      heroDescription: "가입이나 업로드 없이 여러 사진을 완성도 높은 콜라주로 만드세요. 템플릿을 고르고 레이아웃을 조정한 뒤 PNG, JPEG, WebP로 저장하세요.",
      scenarios: [
        { icon: "Sparkles", title: "가입 없음", description: "생일, 여행, 가족, 제품, 행사 콜라주를 계정 없이 빠르게 만드세요." },
        { icon: "ShieldCheck", title: "브라우저 내보내기", description: "개인 사진을 로컬에 둔 채 배치하고 완성 이미지를 다운로드하세요." },
      ],
      faqEntries: [
        { question: "사진 콜라주 만들기는 무료인가요?", answer: "네. 사진 업로드, 템플릿 선택, 스타일 조정, 브라우저 내보내기를 사용할 수 있습니다." },
        { question: "계정이 필요한가요?", answer: "아니요. 에디터를 열면 바로 사용할 수 있습니다." },
        { question: "사진이 업로드되나요?", answer: "아니요. 파일은 브라우저에 머물고 그곳에서 내보내집니다." },
      ],
    },
    {
      slug: "picture-grid-maker",
      title: "온라인 이미지 그리드 만들기 - 무료 비공개 | ImgSplit",
      description: "제품 세트, 무드보드, 포트폴리오, 소셜 게시물용 이미지 그리드를 만들고 간격을 조정해 비공개로 내보내세요.",
      ogTitle: "온라인 이미지 그리드 만들기",
      ogDescription: "브라우저에서 깔끔한 이미지 그리드를 만드세요.",
      overline: "이미지 그리드",
      headlinePart1: "이미지",
      headlineAccent: "그리드",
      headlinePart2: " 만들기",
      heroDescription: "이미지를 일정한 간격, 둥근 모서리, 배경을 가진 깔끔한 그리드로 배치하세요. 이미지 세트, 비교, 참고 자료, 소셜 비주얼에 좋습니다.",
      scenarios: [
        { icon: "Grid3X3", title: "이미지 세트", description: "관련 이미지를 2, 3, 4, 5, 6프레임 레이아웃에 배치하세요." },
        { icon: "Images", title: "시각 비교", description: "제품 사진, 전후 비교, 참고 이미지, 크리에이티브 방향을 한 장으로 비교하세요." },
      ],
      faqEntries: [
        { question: "이미지 그리드와 콜라주의 차이는 무엇인가요?", answer: "이미지 그리드는 반복 프레임과 일정한 간격으로 더 구조적입니다. 각 이미지 위치도 조정할 수 있습니다." },
        { question: "정사각형 이미지 그리드를 만들 수 있나요?", answer: "네. 정사각형 아트보드와 그리드 템플릿을 사용하세요." },
        { question: "빈 칸을 남길 수 있나요?", answer: "네. 빈 프레임은 나중에 클릭하거나 파일을 드롭해 채울 수 있습니다." },
      ],
    },
    {
      slug: "instagram-collage-maker",
      title: "온라인 Instagram 콜라주 만들기 | ImgSplit",
      description: "Instagram 게시물, Story, 요약, 제품 세트용 콜라주를 만들고 정사각형 또는 세로 템플릿으로 비공개 내보내세요.",
      ogTitle: "Instagram 콜라주 만들기",
      ogDescription: "브라우저에서 Instagram용 사진 콜라주를 만드세요.",
      overline: "Instagram 콜라주",
      headlinePart1: "Instagram",
      headlineAccent: "콜라주",
      headlinePart2: " 만들기",
      heroDescription: "정사각형 피드 콜라주, 세로 Story 레이아웃, 요약 게시물, 제품 세트를 소셜 공유에 맞는 템플릿으로 만들고 브라우저에서 내보내세요.",
      scenarios: [
        { icon: "Instagram", title: "Feed와 Story", description: "정사각형 콜라주 보드와 1080x1920 세로 Story 템플릿을 전환하세요." },
        { icon: "Share2", title: "소셜 요약", description: "스타일, 여행, 음식, 행사, 제품 사진을 Instagram에 맞는 한 장으로 합치세요." },
      ],
      faqEntries: [
        { question: "Instagram 게시물과 Stories 둘 다 만들 수 있나요?", answer: "네. 피드에는 정사각형 레이아웃, Stories에는 1080 x 1920 세로 레이아웃을 사용하세요." },
        { question: "간격과 둥근 모서리를 조정할 수 있나요?", answer: "네. 간격, 여백, 반경, 배경, 투명 내보내기 설정을 조정할 수 있습니다." },
        { question: "모바일에서도 작동하나요?", answer: "네. 브라우저 기반이라 데스크톱과 모바일 브라우저에서 사용할 수 있습니다." },
      ],
    },
  ],
  es: [
    {
      slug: "photo-collage-maker",
      title: "Creador de Collages Online - Gratis y Privado | ImgSplit",
      description: "Crea collages de fotos online con plantillas, espacios, fondos y exportación en el navegador. Gratis, privado y sin subir archivos.",
      ogTitle: "Creador de Collages Online",
      ogDescription: "Combina varias fotos en un collage limpio desde el navegador.",
      overline: "Creador de Collages",
      headlinePart1: "Crea ",
      headlineAccent: "Collages",
      headlinePart2: "Online",
      heroDescription: "Combina fotos de viajes, productos, eventos o redes sociales en un collage pulido con plantillas, espacios, fondos y exportación privada.",
      scenarios: [
        { icon: "Images", title: "Colecciones de recuerdos", description: "Une fotos familiares, viajes, eventos y celebraciones en una imagen equilibrada." },
        { icon: "LayoutTemplate", title: "Plantillas rápidas", description: "Empieza con diseños de dos fotos, cuadrícula, mosaico o Story sin maquetar desde cero." },
      ],
      faqEntries: [
        { question: "¿Este creador de collages es privado?", answer: "Sí. Las imágenes se cargan, organizan y exportan localmente en tu navegador." },
        { question: "¿Puedo ajustar cada foto dentro del marco?", answer: "Sí. Selecciona un marco para arrastrar, ajustar, rellenar, escalar o rotar la foto." },
        { question: "¿Qué formatos puedo exportar?", answer: "Puedes exportar el collage como PNG, JPEG o WebP." },
      ],
    },
    {
      slug: "photo-grid-maker",
      title: "Creador de Cuadrículas de Fotos Online | ImgSplit",
      description: "Haz una cuadrícula de fotos online con diseños de 2, 3, 4, 5 o 6 imágenes. Ajusta espacios, márgenes, fondos y exporta en privado.",
      ogTitle: "Creador de Cuadrículas de Fotos",
      ogDescription: "Crea cuadrículas limpias con plantillas en el navegador.",
      overline: "Cuadrícula de Fotos",
      headlinePart1: "Crea ",
      headlineAccent: "Cuadrículas",
      headlinePart2: "Rápido",
      heroDescription: "Crea cuadrículas estructuradas para portafolios, productos, moodboards y publicaciones sociales con control de espacios, bordes y fondo.",
      scenarios: [
        { icon: "Grid3X3", title: "Productos o portafolio", description: "Muestra varias imágenes con espacios consistentes y tamaño de exportación definido." },
        { icon: "Palette", title: "Moodboards", description: "Agrupa colores, texturas, referencias y estudios visuales en una cuadrícula compartible." },
      ],
      faqEntries: [
        { question: "¿Puedo hacer una cuadrícula 2x2?", answer: "Sí. Usa la plantilla de cuatro cuadros y coloca una imagen en cada marco." },
        { question: "¿Puedo cambiar el espacio entre fotos?", answer: "Sí. Usa los controles de espacio y margen para ajustar separación interior y exterior." },
        { question: "¿Puedo exportar una cuadrícula cuadrada?", answer: "Sí. El lienzo predeterminado es 1080 x 1080 y puedes elegir otros tamaños." },
      ],
    },
    {
      slug: "instagram-story-collage",
      title: "Creador de Collages para Instagram Story - 1080x1920 | ImgSplit",
      description: "Crea un collage vertical 1080x1920 para Instagram Story con plantillas, fondos, espacios y exportación privada en navegador.",
      ogTitle: "Collage para Instagram Story",
      ogDescription: "Crea collages verticales 1080x1920 para Stories.",
      overline: "Instagram Story Collage",
      headlinePart1: "Crea ",
      headlineAccent: "Stories",
      headlinePart2: "en Collage",
      heroDescription: "Organiza fotos en un collage vertical 1080x1920 con marco principal, imágenes de apoyo, espacios limpios y tamaño listo para exportar.",
      scenarios: [
        { icon: "Smartphone", title: "Recaps de Story", description: "Combina eventos, viajes, comida, outfits o productos en una imagen vertical." },
        { icon: "Share2", title: "Publicación social", description: "Exporta un collage terminado para Instagram Stories y formatos verticales similares." },
      ],
      faqEntries: [
        { question: "¿Qué tamaño tiene el collage Story?", answer: "El preset Story usa 1080 x 1920 píxeles, un formato vertical 9:16 común." },
        { question: "¿Puedo usar un collage cuadrado?", answer: "Sí. Cambia el tamaño de salida a cuadrado o elige otra plantilla." },
        { question: "¿Mis fotos se suben a un servidor?", answer: "No. El collage se renderiza en tu navegador." },
      ],
    },
    {
      slug: "free-photo-collage-maker",
      title: "Creador de Collages Gratis Online | ImgSplit",
      description: "Crea un collage de fotos gratis online con plantillas, cuadrículas, espacios, fondos y exportación privada en el navegador.",
      ogTitle: "Creador de Collages Gratis",
      ogDescription: "Crea collages gratis en el navegador sin subir archivos.",
      overline: "Collage Gratis",
      headlinePart1: "Crea un ",
      headlineAccent: "Collage Gratis",
      headlinePart2: "Online",
      heroDescription: "Convierte varias fotos en un collage pulido sin registro ni subida. Elige una plantilla, ajusta el diseño y exporta PNG, JPEG o WebP desde el navegador.",
      scenarios: [
        { icon: "Sparkles", title: "Sin registro", description: "Crea collages de cumpleaños, viajes, familia, productos o eventos sin abrir una cuenta." },
        { icon: "ShieldCheck", title: "Exportación privada", description: "Mantén tus fotos personales en el navegador mientras organizas y descargas el collage final." },
      ],
      faqEntries: [
        { question: "¿El creador de collages es gratis?", answer: "Sí. Puedes subir fotos, elegir plantillas, ajustar estilos y exportar desde el navegador." },
        { question: "¿Necesito una cuenta?", answer: "No. El editor se abre al instante y funciona sin registro." },
        { question: "¿Se suben mis fotos?", answer: "No. Los archivos permanecen en tu navegador mientras creas y exportas el collage." },
      ],
    },
    {
      slug: "picture-grid-maker",
      title: "Creador de Cuadrículas de Imágenes Online | ImgSplit",
      description: "Crea una cuadrícula de imágenes para productos, moodboards, portafolios y redes sociales. Ajusta espacios y exporta en privado.",
      ogTitle: "Creador de Cuadrículas de Imágenes",
      ogDescription: "Crea cuadrículas limpias con exportación privada en el navegador.",
      overline: "Cuadrícula de Imágenes",
      headlinePart1: "Crea una ",
      headlineAccent: "Cuadrícula",
      headlinePart2: "Online",
      heroDescription: "Organiza imágenes en una cuadrícula limpia con separaciones, bordes y fondos consistentes. Úsala para comparaciones, referencias y visuales sociales.",
      scenarios: [
        { icon: "Grid3X3", title: "Conjuntos de imágenes", description: "Coloca imágenes relacionadas en diseños de dos, tres, cuatro, cinco o seis marcos." },
        { icon: "Images", title: "Comparaciones visuales", description: "Compara productos, antes y después, referencias o direcciones creativas en una sola exportación." },
      ],
      faqEntries: [
        { question: "¿Cuál es la diferencia entre cuadrícula y collage?", answer: "Una cuadrícula es más estructurada, con marcos repetidos y espacios consistentes. También puedes ajustar cada imagen." },
        { question: "¿Puedo crear una cuadrícula cuadrada?", answer: "Sí. Usa el lienzo cuadrado y elige una plantilla de cuadrícula." },
        { question: "¿Puedo dejar espacios vacíos?", answer: "Sí. Los marcos vacíos se pueden rellenar después haciendo clic o soltando un archivo." },
      ],
    },
    {
      slug: "instagram-collage-maker",
      title: "Creador de Collages para Instagram Online | ImgSplit",
      description: "Crea collages para posts, Stories, recaps y productos de Instagram. Usa plantillas cuadradas o verticales con exportación privada.",
      ogTitle: "Creador de Collages para Instagram",
      ogDescription: "Crea collages listos para Instagram desde el navegador.",
      overline: "Collage para Instagram",
      headlinePart1: "Diseña ",
      headlineAccent: "Collages",
      headlinePart2: "para Instagram",
      heroDescription: "Crea collages cuadrados para feed, diseños verticales para Story, recaps o productos con plantillas pensadas para compartir en redes.",
      scenarios: [
        { icon: "Instagram", title: "Feed y Story", description: "Cambia entre lienzos cuadrados y plantillas verticales 1080x1920 para Stories." },
        { icon: "Share2", title: "Recaps sociales", description: "Combina outfits, viajes, comida, eventos o productos en una imagen lista para Instagram." },
      ],
      faqEntries: [
        { question: "¿Puedo hacer collages para posts y Stories?", answer: "Sí. Usa un diseño cuadrado para feed o uno de 1080 x 1920 para Stories." },
        { question: "¿Puedo controlar espacios y esquinas redondeadas?", answer: "Sí. Ajusta espacios, márgenes, radio, fondo y exportación transparente." },
        { question: "¿Funciona en móvil?", answer: "Sí. El editor funciona en navegadores de escritorio y móviles." },
      ],
    },
  ],
}

function createPages(locale: LocaleKey): Record<string, ToolPageData> {
  return Object.fromEntries(
    seeds[locale].map((seed) => [
      seed.slug,
      {
        slug: seed.slug,
        category: "use-case",
        seo: {
          title: seed.title,
          description: seed.description,
          ogTitle: seed.ogTitle,
          ogDescription: seed.ogDescription,
        },
        hero: {
          overline: seed.overline,
          headlinePart1: seed.headlinePart1,
          headlineAccent: seed.headlineAccent,
          headlinePart2: seed.headlinePart2,
          description: seed.heroDescription,
        },
        scenarios: seed.scenarios,
        howToSteps: howToSteps[locale],
        faqEntries: seed.faqEntries,
        relatedTools: relatedTools[locale],
      },
    ])
  )
}

export const collagePagesByLocale: LocaleCollagePages = {
  en: createPages("en"),
  "zh-CN": createPages("zh-CN"),
  ja: createPages("ja"),
  ko: createPages("ko"),
  es: createPages("es"),
}
